app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, flash, redirect, render_template, url_for, request
from flask_login import login_required, current_user

from . import home
from .. import db

from ..admin.forms import UserEditForm, InviteEditForm
from ..models import User, Invites, Company, Mapping, Role

@home.route('/')
def homepage():

    return render_template('home/index.html', title='Welcome to Squad Master')


@home.route('/dashboard')
@login_required
def dashboard():
    return render_template('home/dashboard.html', title='Dashboard')


@home.route('/admin/companies')
@login_required
def admin_companies():
    if not current_user.is_super_admin:
        abort(403)
    return render_template('home/admin_companies.html', title='Admin Companies')


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    if not current_user.is_admin:
        abort(403)
    return render_template('home/admin_dashboard.html', title='Admin Dashboard')


@home.route('/profile', methods=['GET'])
@login_required
def profile():

    return render_template('home/profilepage.html', title='Employee Profile', edit_profile=False)

@home.route('/profile/edit', methods=['GET','POST'])
@login_required
def edit_profile():

    form = UserEditForm(obj=current_user)
    if form.validate_on_submit():
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        try:
            db.session.add(current_user)
            db.session.commit()
            flash('You have successfully update your profile')
        except Exception, e:
            flash('Error in updating profile. ' + str(e))
        return redirect(url_for('home.profile'))

    return render_template('home/profilepage.html',form=form, title='Edit Profile', edit_profile=True)

@home.route('/invite', methods=['GET','POST'])
def add_invite():

    email = request.args.get('email')
    invite = Invites.query.filter_by(email=email)
    if not invite:
        abort(404)
    company = invite.first().company
    user = User(email=email)
    form = InviteEditForm(obj=user)
    emp_role = Role.query.filter_by(name='employee').first()
    if form.validate_on_submit():
        user.first_name = form.fname.data
        user.last_name = form.lname.data
        user.password =  form.password.data
        user.role_id = emp_role.id
        try:
            db.session.add(user)
            mapping = Mapping(user_id=user.id)
            company.users.append(mapping)
            db.session.add(mapping)
            db.session.add(company)
            db.session.commit()
            flash('You have successfully update your profile. Please login')
        except Exception, e:
            flash('Error in updating profile. ' + str(e))
        return redirect(url_for('auth.login'))

    return render_template('home/invitee.html',form=form, title='Edit Profile')

app/templates/home/admin_companies.html
{% extends "base.html" %} {% block title %}Super Admin Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>Manage your Companies</h3>
                    <br>
                    <br>
                    <a href="{{ url_for('admin.list_companies') }}" id="db">Company Database</a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/admin_dashboard.html
{% extends "base.html" %} {% block title %}Admin Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>Manage your Employees</h3>
                    <br>
                    <br>
                    <a href="{{ url_for('admin.list_employees') }}" id="db">Employee Database</a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/dashboard.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Hello {{current_user.first_name}}</h1>
                    <h3>Welcome to EMS. Let's Get Started</h3>
                    </ul>
                    <br>
                    <br>
                    <a href="{{ url_for('home.profile') }}" id="profilebtn">View your profile</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}
<p id="message">
    Manage your employees in a easy way. You have complete control over the details of the registered employees.
</p>
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Employee Management System</h1>
                    <h3>Manage your employees in the most perfect way</h3>
                    </ul>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/invitee.html
{% import "bootstrap/wtf.html" as wtf %} {% extends "base.html" %} {% block title %} {% endblock %} {% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <div class="center">
                    <br/> {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/profilepage.html
{% import "bootstrap/wtf.html" as wtf %} {% extends "base.html" %} {% block title %}View Profile{% endblock %}
{% block body %}
<div id="mainwrap">
{% if edit_profile %}
    <div class="content-section">
    <div class="outer">
        <div class="middle">
            <img src="../../static/img/avatar.png" id="avatar">
            <div class="inner">
                <div class="center">

                {{ wtf.quick_form(form) }}
                </div>
            </div>
        </div>
    </div>
    </div>
    {% else %}

        <img src="../../static/img/avatar.png" id="avatar">
        <p id="cname">{{current_user.first_name}} {{current_user.last_name}} - {{ current_user.role.display_name }}</p>
        <br>
        <div> <span id="mail"><i class="fa fa-envelope"></i><a href="mailto:{{current_user.email}}">  {{current_user.email}}</a></span></div>

        <br>
            <div style="text-align: center">
                            <hr class="intro-divider">
                            <a href="{{ url_for('home.edit_profile') }}" class="btn btn-default btn-lg">
                                <i class="fa fa-plus"></i> Edit
                            </a>
            </div>
 {%  endif %}
</div>
{% endblock %}